//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Mvc.Easy.Cms.Edit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Mvc.Easy.Cms.Edit.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Buttons_Change_Password {
            get {
                return ResourceManager.GetString("Buttons_Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Buttons_Delete {
            get {
                return ResourceManager.GetString("Buttons_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Buttons_Edit {
            get {
                return ResourceManager.GetString("Buttons_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit page data.
        /// </summary>
        internal static string Buttons_Edit_Page_Data {
            get {
                return ResourceManager.GetString("Buttons_Edit_Page_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Buttons_File {
            get {
                return ResourceManager.GetString("Buttons_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Buttons_Image {
            get {
                return ResourceManager.GetString("Buttons_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline.
        /// </summary>
        internal static string Buttons_Inline {
            get {
                return ResourceManager.GetString("Buttons_Inline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Buttons_Log_Out {
            get {
                return ResourceManager.GetString("Buttons_Log_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Buttons_Preview {
            get {
                return ResourceManager.GetString("Buttons_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Buttons_Properties {
            get {
                return ResourceManager.GetString("Buttons_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Buttons_Save {
            get {
                return ResourceManager.GetString("Buttons_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server explorer.
        /// </summary>
        internal static string Buttons_Server_Explorer {
            get {
                return ResourceManager.GetString("Buttons_Server_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string SE_Buttons_Delete {
            get {
                return ResourceManager.GetString("SE_Buttons_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string SE_Buttons_New_Folder {
            get {
                return ResourceManager.GetString("SE_Buttons_New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string SE_Buttons_Rename {
            get {
                return ResourceManager.GetString("SE_Buttons_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SE_Buttons_Select {
            get {
                return ResourceManager.GetString("SE_Buttons_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string SE_Buttons_Upload {
            get {
                return ResourceManager.GetString("SE_Buttons_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SE_Titles_Name {
            get {
                return ResourceManager.GetString("SE_Titles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root.
        /// </summary>
        internal static string SE_Titles_Root_Name {
            get {
                return ResourceManager.GetString("SE_Titles_Root_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string SE_Titles_Size {
            get {
                return ResourceManager.GetString("SE_Titles_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory with such name already exists..
        /// </summary>
        internal static string SE_Validation_Directory_Already_Exists {
            get {
                return ResourceManager.GetString("SE_Validation_Directory_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with such name already exists..
        /// </summary>
        internal static string SE_Validation_File_Already_Exists {
            get {
                return ResourceManager.GetString("SE_Validation_File_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name has path invalid characters..
        /// </summary>
        internal static string SE_Validation_Name_Has_Invalid_Chars {
            get {
                return ResourceManager.GetString("SE_Validation_Name_Has_Invalid_Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Text_Ajax_Loading {
            get {
                return ResourceManager.GetString("Text_Ajax_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string Text_Confirm_Delete {
            get {
                return ResourceManager.GetString("Text_Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL:.
        /// </summary>
        internal static string Text_ImageSelector_EnterUrl {
            get {
                return ResourceManager.GetString("Text_ImageSelector_EnterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Text_ImageSelector_Select {
            get {
                return ResourceManager.GetString("Text_ImageSelector_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Text_ImageSelector_Submit {
            get {
                return ResourceManager.GetString("Text_ImageSelector_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string Titles_Account_Confirm_Password {
            get {
                return ResourceManager.GetString("Titles_Account_Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string Titles_Account_New_Password {
            get {
                return ResourceManager.GetString("Titles_Account_New_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string Titles_Account_Old_Password {
            get {
                return ResourceManager.GetString("Titles_Account_Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Titles_Account_Password {
            get {
                return ResourceManager.GetString("Titles_Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string Titles_Account_User_Name {
            get {
                return ResourceManager.GetString("Titles_Account_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN PANEL.
        /// </summary>
        internal static string Titles_Admin_Panel {
            get {
                return ResourceManager.GetString("Titles_Admin_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Titles_ChangePassword {
            get {
                return ResourceManager.GetString("Titles_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        internal static string Titles_CreateFolder {
            get {
                return ResourceManager.GetString("Titles_CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit - .
        /// </summary>
        internal static string Titles_EditItem {
            get {
                return ResourceManager.GetString("Titles_EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Titles_Login {
            get {
                return ResourceManager.GetString("Titles_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file - .
        /// </summary>
        internal static string Titles_OpenFile {
            get {
                return ResourceManager.GetString("Titles_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page data.
        /// </summary>
        internal static string Titles_PageData {
            get {
                return ResourceManager.GetString("Titles_PageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Titles_Page_Data_Name {
            get {
                return ResourceManager.GetString("Titles_Page_Data_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string Titles_Page_Data_Storage_Local {
            get {
                return ResourceManager.GetString("Titles_Page_Data_Storage_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Titles_Page_Data_Value {
            get {
                return ResourceManager.GetString("Titles_Page_Data_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Titles_Rename {
            get {
                return ResourceManager.GetString("Titles_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server explorer.
        /// </summary>
        internal static string Titles_ServerExplorer {
            get {
                return ResourceManager.GetString("Titles_ServerExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Titles_Upload {
            get {
                return ResourceManager.GetString("Titles_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item.
        /// </summary>
        internal static string Title_Repeater_NewItem {
            get {
                return ResourceManager.GetString("Title_Repeater_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Confirm password&apos; and &apos;New password&apos; do not match..
        /// </summary>
        internal static string Validation_Account_Comapre_Passwords {
            get {
                return ResourceManager.GetString("Validation_Account_Comapre_Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required..
        /// </summary>
        internal static string Validation_Account_Confirm_Password_Required {
            get {
                return ResourceManager.GetString("Validation_Account_Confirm_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required..
        /// </summary>
        internal static string Validation_Account_New_Password_Required {
            get {
                return ResourceManager.GetString("Validation_Account_New_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is required..
        /// </summary>
        internal static string Validation_Account_Old_Password_Required {
            get {
                return ResourceManager.GetString("Validation_Account_Old_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string Validation_Account_Password_Required {
            get {
                return ResourceManager.GetString("Validation_Account_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required..
        /// </summary>
        internal static string Validation_Account_User_Name_Required {
            get {
                return ResourceManager.GetString("Validation_Account_User_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        internal static string Validation_Invalid_Credentials {
            get {
                return ResourceManager.GetString("Validation_Invalid_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password provided is incorrect..
        /// </summary>
        internal static string Validation_Old_Password_Invalid {
            get {
                return ResourceManager.GetString("Validation_Old_Password_Invalid", resourceCulture);
            }
        }
    }
}
